### ISSUE TITLE
Not working on macOS?

### ISSUE THREAD

**Issue by MBilderbeek** [kenchan0130/actions-system-info#73]
Tried your useful action in my workflow, but it failed on macOS, when using the master version:
```
Run kenchan0130/actions-system-info@master
Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```
The same happens with v1.0.0:
```
Run kenchan0130/actions-system-info@v1.0.0
Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```
I hope you can fix it, so I can use it to automatically set the number of jobs for a make command, independent of OS.

**Comment by tbaudier** [comment]
I have the same problem since one week here: https://github.com/OpenGATE/opengate/actions/runs/3325265982/jobs/5536748585#step:5:7

Did you find a workaround ?

**Comment by MBilderbeek** [comment]
I now use:
`          -j ${{ steps.cpu-cores.outputs.count }} \`
instead of 
`          -j ${{ steps.system-info.outputs.cpu-core }} \`
So, a different action:
`       uses: SimenB/github-actions-cpu-cores@v1`

**Comment by kenchan0130** [comment]
@MBilderbeek @tbaudier 

I re-ran the test job as the regular test had stopped.

https://github.com/kenchan0130/actions-system-info/actions/runs/3801450081/jobs/6465932003

The CPU core counts are being appropriately obtained in the macOS build results.

If you continue to experience problems, please let me know.

**Comment by jdogmcsteezy** [comment]
I am having the same issue on macOS 12.  The action ran fine on macOS 10 and 11. Here is an image of the failure.  Not much info there. The only change was the macOS version.
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/22361806/215163486-ea005bae-7658-45b1-9390-aacd8a2a3787.png">

**Comment by jdogmcsteezy** [comment]
In my case #71 looks to be the fix.  macos-release added support for macOS 12 in 2.5.  It looks like the [tests](https://github.com/kenchan0130/actions-system-info/actions/runs/3801537406/jobs/6466109247) are failing because jest does not like an import statement.  I don't know much about javascript unfortunately

**Comment by kenchan0130** [comment]
I have merged https://github.com/kenchan0130/actions-system-info/pull/71 PR.
If the problem persists in your environment, you can feel free to reopen this issue.
