### ISSUE TITLE
set-output command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by navidemad** [kenchan0130/actions-system-info#83]
Hello, thanks for the github action.
Is it possible to fix the following warning ?

```sh
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
```
For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by kenchan0130** [comment]
I have updated @actions/core npm library to the latest version.
If the WARNING persists, it is probably related to [the issue](https://github.com/actions/toolkit/issues/1218).
